"""Render Grafana provisioning for each F´ deployment."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
from collections.abc import Sequence
from pathlib import Path

from proves_yamcs.deployments import DeploymentError, ResolvedDeployment

DATASOURCE_UID = "jaops-yamcs-main"
_UID_UNSAFE = re.compile(r"[^A-Za-z0-9-]+")


def _atomic_text(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False
    ) as stream:
        stream.write(content)
        temporary = Path(stream.name)
    temporary.chmod(mode)
    os.replace(temporary, path)


def dashboard_uid(deployment: str, stem: str) -> str:
    """Return a Grafana-safe uid unique to this deployment layout."""
    raw = _UID_UNSAFE.sub("-", f"yamcs-{deployment}-{stem}").strip("-")
    if not raw:
        raw = "yamcs-dashboard"
    if len(raw) <= 40:
        return raw
    digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:8]
    return f"{raw[:31].rstrip('-')}-{digest}"


def endpoint_name(deployment: str, processor: str) -> str:
    return f"{deployment}_{processor}"


def placeholders(item: ResolvedDeployment, *, stem: str) -> dict[str, str]:
    return {
        "__DASHBOARD_UID__": dashboard_uid(item.name, stem),
        "__DEPLOYMENT__": item.name,
        "__INSTANCE__": item.instance,
        "__ENDPOINT__": endpoint_name(item.name, "realtime"),
        "__ENDPOINT_REPLAY__": endpoint_name(item.name, "replay"),
        "__SCID__": str(item.spacecraft_id),
        "__TM_PORT__": str(item.tm_port),
        "__TC_PORT__": str(item.tc_port),
    }


def apply_placeholders(text: str, mapping: dict[str, str]) -> str:
    for key, value in mapping.items():
        text = text.replace(key, value)
    return text


def render_datasource_yaml(deployments: Sequence[ResolvedDeployment]) -> str:
    lines = [
        "# Generated by proves-yamcs-prepare. Do not edit.",
        "apiVersion: 1",
        "prune: true",
        "",
        "datasources:",
        "  - name: JAOPS Yamcs",
        f"    uid: {DATASOURCE_UID}",
        "    type: jaops-yamcs-datasource",
        "    access: proxy",
        "    orgId: 1",
        "    isDefault: true",
        "    editable: true",
        "    jsonData:",
        "      hosts:",
        "        yamcs:",
        "          name: PROVES Yamcs",
        "          description: Central Yamcs instance on the compose network",
        "          path: yamcs:8090",
        "          tlsEnabled: false",
        "          tlsInsecure: false",
        "          authEnabled: false",
        "          protobuf: true",
        "      endpoints:",
    ]
    for item in deployments:
        for processor, label in (
            ("realtime", "Live processor"),
            ("replay", "Archive replay processor"),
        ):
            key = endpoint_name(item.name, processor)
            lines.append(f'        "{key}":')
            lines.append(f"          name: {item.name} {processor}")
            lines.append(f"          description: {label} for the {item.name} instance")
            lines.append("          host: yamcs")
            lines.append(f"          instance: {item.name}")
            lines.append(f"          processor: {processor}")
    return "\n".join(lines) + "\n"


def _write_dashboard(source: Path, destination: Path, mapping: dict[str, str]) -> None:
    rendered = apply_placeholders(source.read_text(encoding="utf-8"), mapping)
    payload = json.loads(rendered)
    if not isinstance(payload, dict):
        raise DeploymentError(f"Grafana dashboard template must be an object: {source}")
    _atomic_text(destination, json.dumps(payload, indent=2) + "\n")


def _clear_generated_dashboards(dashboards_json_dir: Path) -> None:
    if dashboards_json_dir.is_dir():
        shutil.rmtree(dashboards_json_dir)
    dashboards_json_dir.mkdir(parents=True, exist_ok=True)


def _copy_static_provisioning(grafana_dir: Path, grafana_runtime: Path) -> None:
    """Copy plugin/alerting/provider YAML into the generated provisioning tree."""
    source = grafana_dir / "provisioning"
    for name in ("plugins", "alerting"):
        src = source / name
        dest = grafana_runtime / name
        if dest.exists():
            if dest.is_dir():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        if src.is_dir():
            shutil.copytree(src, dest)
    provider = source / "dashboards" / "dashboards.yaml"
    if not provider.is_file():
        raise DeploymentError(f"Grafana dashboard provider not found: {provider}")
    destination = grafana_runtime / "dashboards" / "dashboards.yaml"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(provider, destination)


def render_grafana(
    deployments: Sequence[ResolvedDeployment],
    grafana_dir: Path,
    runtime_dir: Path,
) -> Path:
    """Write a complete Grafana provisioning tree for Compose to mount."""
    if not deployments:
        raise DeploymentError("at least one deployment is required")
    templates_dir = grafana_dir / "templates"
    if not templates_dir.is_dir():
        raise DeploymentError(f"Grafana templates directory not found: {templates_dir}")
    templates = sorted(templates_dir.glob("*.json"))
    if not templates:
        raise DeploymentError(f"no Grafana dashboard templates in {templates_dir}")

    grafana_runtime = runtime_dir / "grafana"
    dashboards_dir = grafana_runtime / "dashboards"
    json_dir = dashboards_dir / "json"
    _copy_static_provisioning(grafana_dir, grafana_runtime)
    _clear_generated_dashboards(json_dir)
    for leftover in dashboards_dir.iterdir():
        if leftover.name in {"json", "dashboards.yaml"}:
            continue
        if leftover.is_dir():
            shutil.rmtree(leftover)
        else:
            leftover.unlink()
    _atomic_text(
        grafana_runtime / "datasources" / "yamcs.yaml",
        render_datasource_yaml(deployments),
    )

    extras_root = grafana_dir / "dashboards"
    for item in deployments:
        folder = json_dir / item.name
        folder.mkdir(parents=True, exist_ok=True)
        for template in templates:
            mapping = placeholders(item, stem=template.stem)
            _write_dashboard(template, folder / template.name, mapping)
        extra_dir = extras_root / item.name
        if extra_dir.is_dir():
            for extra in sorted(extra_dir.glob("*.json")):
                mapping = placeholders(item, stem=extra.stem)
                _write_dashboard(extra, folder / extra.name, mapping)

    home_source = json_dir / deployments[0].name / "overview.json"
    if not home_source.is_file():
        generated = sorted((json_dir / deployments[0].name).glob("*.json"))
        if not generated:
            raise DeploymentError("Grafana rendering produced no dashboards")
        home_source = generated[0]
    shutil.copyfile(home_source, grafana_runtime / "home.json")
    return grafana_runtime
