"""Generate Yamcs runtime configuration from a deployments manifest."""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import subprocess
import tempfile
import xml.etree.ElementTree as ET
from collections.abc import Mapping, Sequence
from pathlib import Path

from proves_yamcs.bundle import RuntimeBundle
from proves_yamcs.deployments import (
    MANIFEST_FILENAME,
    DeploymentError,
    ResolvedDeployment,
    load_deployment_specs,
    resolve_deployments,
    write_runtime_manifest,
)
from proves_yamcs.grafana import render_grafana

DEFAULT_ROOT_CONTAINER = "CCSDSSpacePacket"
GROUND_XTCE_NAME = "ground-control.xtce.xml"
INSTANCE_TEMPLATE = "yamcs.instance.yaml.template"
COMPOSE_OVERLAY_NAME = "compose.udp.yaml"
DEFAULT_GRAFANA_DIR = Path(__file__).resolve().parents[2] / "grafana"


def _atomic_text(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False
    ) as stream:
        stream.write(content)
        temporary = Path(stream.name)
    temporary.chmod(mode)
    os.replace(temporary, path)


def _server_secret(runtime_dir: Path) -> str:
    path = runtime_dir / "secrets" / "yamcs-secret-key"
    if path.exists():
        value = path.read_text(encoding="ascii").strip()
        if len(value) != 64 or any(char not in "0123456789abcdef" for char in value):
            raise ValueError(f"invalid persisted Yamcs secret: {path}")
        return value
    value = secrets.token_hex(32)
    _atomic_text(path, f"{value}\n", 0o600)
    return value


def _clear_generated(config_dir: Path) -> None:
    etc_dir = config_dir / "etc"
    mdb_dir = config_dir / "mdb"
    if etc_dir.is_dir():
        for path in etc_dir.glob("yamcs*.yaml"):
            path.unlink()
    if mdb_dir.is_dir():
        for path in mdb_dir.glob("*.xtce.xml"):
            if path.name != GROUND_XTCE_NAME:
                path.unlink()


def render_compose_overlay(
    deployments: Sequence[ResolvedDeployment], path: Path
) -> None:
    home = (
        f"/etc/grafana/provisioning/dashboards/json/{deployments[0].name}/overview.json"
    )
    lines = [
        "# Generated by proves-yamcs-prepare. Do not edit.",
        "services:",
        "  yamcs:",
        "    ports:",
    ]
    for item in deployments:
        lines.append(f'      - "127.0.0.1:{item.tm_port}:{item.tm_port}/udp"')
    lines.extend(
        [
            "  grafana:",
            "    environment:",
            f"      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: {home}",
        ]
    )
    _atomic_text(path, "\n".join(lines) + "\n")


def render_configuration(
    deployments: Sequence[ResolvedDeployment],
    template_dir: Path,
    runtime_dir: Path,
    *,
    ground_xtce_source: Path | None = None,
    tm_root_containers: Mapping[str, str] | None = None,
    grafana_dir: Path | None = None,
    clear: bool = True,
) -> Path:
    """Render all server configuration and return its root directory."""
    if not deployments:
        raise DeploymentError("at least one deployment is required")
    config_dir = runtime_dir / "config"
    etc_dir = config_dir / "etc"
    mdb_dir = config_dir / "mdb"
    etc_dir.mkdir(parents=True, exist_ok=True)
    mdb_dir.mkdir(parents=True, exist_ok=True)
    if clear:
        _clear_generated(config_dir)
    secret = _server_secret(runtime_dir)
    roots = tm_root_containers or {}

    instance_lines = "\n".join(f"  - {item.name}" for item in deployments)
    global_template = (template_dir / "yamcs.yaml.template").read_text(encoding="utf-8")
    _atomic_text(
        etc_dir / "yamcs.yaml",
        global_template.replace("@YAMCS_SECRET_KEY@", secret).replace(
            "@INSTANCES@", instance_lines
        ),
    )

    instance_template = (template_dir / INSTANCE_TEMPLATE).read_text(encoding="utf-8")
    for item in deployments:
        root_container = roots.get(item.name, "/PLACEHOLDER/CCSDSSpacePacket")
        instance_config = (
            instance_template.replace("@SPACECRAFT_ID@", str(item.spacecraft_id))
            .replace("@FRAME_LENGTH@", str(item.frame_length))
            .replace("@TM_ROOT_CONTAINER@", root_container)
            .replace("@TM_PORT@", str(item.tm_port))
            .replace("@TC_PORT@", str(item.tc_port))
            .replace("@MDB_FILE@", item.mdb_file)
        )
        _atomic_text(etc_dir / f"yamcs.{item.name}.yaml", instance_config)

    shutil.copyfile(template_dir / "processor.yaml", etc_dir / "processor.yaml")
    source = ground_xtce_source or (
        Path(__file__).resolve().parents[2] / "config" / "mdb" / GROUND_XTCE_NAME
    )
    shutil.copyfile(source, mdb_dir / GROUND_XTCE_NAME)
    render_compose_overlay(deployments, runtime_dir / COMPOSE_OVERLAY_NAME)
    write_runtime_manifest(deployments, config_dir / MANIFEST_FILENAME)
    render_grafana(deployments, grafana_dir or DEFAULT_GRAFANA_DIR, runtime_dir)
    return config_dir


def generate_xtce(bundle: RuntimeBundle, config_dir: Path, mdb_file: str) -> Path:
    output = config_dir / "mdb" / mdb_file
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["fprime-to-xtce", str(bundle.dictionary_path), "-o", str(output)],
        check=True,
    )
    validate_xtce(output)
    return output


def xtce_space_system_name(path: Path) -> str:
    root = ET.parse(path).getroot()
    name = root.attrib.get("name")
    if not name:
        raise ValueError(f"XTCE root space system is missing a name: {path}")
    return name


def tm_root_container_path(xtce_path: Path) -> str:
    space_system = xtce_space_system_name(xtce_path)
    return f"/{space_system}/{DEFAULT_ROOT_CONTAINER}"


def validate_xtce(path: Path) -> None:
    root = ET.parse(path).getroot()
    name = root.attrib.get("name")
    if not name:
        raise ValueError(f"XTCE root space system is missing a name: {path}")
    containers = {
        element.attrib.get("name")
        for element in root.iter()
        if element.tag.rsplit("}", 1)[-1] == "SequenceContainer"
    }
    if DEFAULT_ROOT_CONTAINER not in containers:
        raise ValueError(
            f"XTCE does not contain required root container {DEFAULT_ROOT_CONTAINER!r}"
        )


def prepare(
    deployments_file: Path,
    runtime_dir: Path,
    template_dir: Path,
    grafana_dir: Path | None = None,
) -> tuple[ResolvedDeployment, ...]:
    specs = load_deployment_specs(deployments_file)
    deployments = resolve_deployments(specs)
    grafana = grafana_dir or DEFAULT_GRAFANA_DIR
    for directory in ("data", "cache", "pids", "state"):
        (runtime_dir / directory).mkdir(parents=True, exist_ok=True)
    config_dir = render_configuration(
        deployments, template_dir, runtime_dir, grafana_dir=grafana
    )
    roots: dict[str, str] = {}
    for item in deployments:
        xtce_path = generate_xtce(item.bundle, config_dir, item.mdb_file)
        roots[item.name] = tm_root_container_path(xtce_path)
    render_configuration(
        deployments,
        template_dir,
        runtime_dir,
        tm_root_containers=roots,
        grafana_dir=grafana,
        clear=False,
    )
    summary = ", ".join(
        f"{item.name} SCID {item.spacecraft_id} TM :{item.tm_port}"
        for item in deployments
    )
    print(f"Prepared Yamcs configuration ({summary}) at {config_dir}")
    return deployments


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--deployments-file",
        type=Path,
        default=Path("config/deployments.toml"),
    )
    parser.add_argument("--runtime-dir", type=Path, default=Path("runtime"))
    parser.add_argument("--template-dir", type=Path, default=Path("config/etc"))
    parser.add_argument("--grafana-dir", type=Path, default=DEFAULT_GRAFANA_DIR)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    prepare(
        args.deployments_file,
        args.runtime_dir,
        args.template_dir,
        grafana_dir=args.grafana_dir,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
