apiVersion: 1
prune: true

datasources:
  - name: JAOPS Yamcs
    uid: jaops-yamcs-main
    type: jaops-yamcs-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      hosts:
        yamcs:
          name: PROVES Yamcs
          description: Central Yamcs instance on the compose network
          path: yamcs:8090
          tlsEnabled: false
          tlsInsecure: false
          authEnabled: false
          protobuf: true
      endpoints:
        proves-flight_realtime:
          name: proves-flight realtime
          description: Live processor for the proves-flight instance
          host: yamcs
          instance: proves-flight
          processor: realtime
        proves-flight_replay:
          name: proves-flight replay
          description: Archive replay processor for the proves-flight instance
          host: yamcs
          instance: proves-flight
          processor: replay
